#!/usr/bin/env python3

# imports
import argparse
import sys
import welcome
import random
import json
import requests

# arguments
class argParser(argparse.ArgumentParser):
    def parseError(self, message):
        sys.stderr.write('ERROR: %s\n' % message)
        self.print_help()
        sys.exit

parser = argParser()
parser.add_argument('message', type=str, help='the message you want to sendo to Discord')
args = parser.parse_args()

def sendToDiscord(webhook_url, message):
    """
    Post a message to discord API via a Webhook.
    """
    payload = {
        "content": message
    }
    headers = {
        'Content-Type': 'application/json',
    }
    response = requests.post(webhook_url, data=json.dumps(payload), headers=headers)
    print(response)



# setup for sendToDiscord
webhook_url = 'https://discordapp.com/api/webhooks/666549658042236928/s51FyzoloKv0gb1wdnMbAI10g3LuNBTSrtSonzUL9ILVuTMwPTnCC2weqRvQ-UPtJzUP'
if 'welcome' in args.message:
    message = random.choice(welcome.welcomeList)
else:
    message = args.message

sendToDiscord(webhook_url, message)